### ISSUE TITLE
Don't store plaintext passwords

### ISSUE THREAD

**Issue by tloriato** [sdec-brasil/dashboard#38]
You know... for safety reasons

**Comment by dbeyda** [comment]
Implemented password hashing and salting based on [this article](https://crackstation.net/hashing-security.htm). Used [bcrypt](https://www.npmjs.com/package/bcrypt) library for genearting unique salts, hashing and validating the passwords. Since bcrypt stores the hash together in the password string, I didn't need to create a new hash column on the database.

* Added beforeSave hooks in sequelize, that will hash the password when a user or client is created/updated and his password has changed.

* Changed the validate password functions for user and client.
* Fixed a small bug in clientCredentials authentication.
* Tested all authentication strategies.
